apiVersion: v1
kind: Pod
metadata:
  name: webchart-pod
  labels:
    app: webchart
spec:
  containers:
  - name: main
    image: httpd:2.4.51
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/local/apache2/htdocs
  volumes:
  - name: html
    configMap:
      name: webchart-cm