apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2-frontend-dep
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: funfacts-fe
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: funfacts-fe
    spec:
      containers:
      - name: funfacts-fe-con
        image:  shekeriev/k8s-facts-fe
        ports:
        - containerPort: 5000
        env:
        - name: FACTS_SERVER
          value: "funfacts-be-svc"
        - name: FACTS_PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: funfacts-fe-svc
  labels:
    app: funfacts-fe
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30001
    protocol: TCP
  selector:
    app: funfacts-fe
