apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc10gb
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      purpose: demo