apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devguru
  namespace: projectx
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - deployments
  - replicasets
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - pods
  - deployments
  - replicasets
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  