apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ivan-rb
  namespace: projectx
subjects:
- kind: User
  name: ivan
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devguru
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mariana-rb
  namespace: projectx
subjects:
- kind: User
  name: mariana
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devguru
  apiGroup: rbac.authorization.k8s.io
