apiVersion: v1
kind: ResourceQuota
metadata:
  name: projectx-quota
  namespace: projectx
spec:
  hard:
    pods: 10
    services: 10
    requests.cpu: 1
    requests.memory: 1Gi
    limits.cpu: 2
    limits.memory: 2Gi
    count/deployments.apps: 2
    count/replicasets.apps: 2
    