apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: reslim
spec:
  containers:
  - image: busybox
    command: ["dd", "if=/dev/zero", "of=/dev/null", "bs=32M"]
    name: main
    resources:
      requests:
        cpu: 250m
        memory: 16Mi