apiVersion: v1
kind: Pod
metadata:
  name: startup-same
spec:
  containers:
  - name: startup
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
    - t=$(( 10 + $RANDOM % 100 )); echo 'Sleep for '$t; sleep $t; touch /tmp/healthy; sleep 60; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      failureThreshold: 22
      periodSeconds: 5