apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-oracle
  namespace: basicnp
spec:
  podSelector:
    matchLabels:
      app: oracle
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: "true"
