apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: web-pod
spec:
  initContainers:
  - name: init-data
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
      - echo 'Hello!' > /var/www/html/index.html
    volumeMounts:
    - name: data
      mountPath: /var/www/html
  containers:
  - name: cont-main
    image: nginx:latest
    volumeMounts:
    - name: data
      mountPath: /var/www/html
  volumes:
  - name: data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: web-svc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: web
