apiVersion: v1
kind: Service
metadata:
  labels:
    app: hw
  name: listener
spec:
  ports:
  - name: listener-port
    nodePort: 32000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: hw
    role: listener
  type: NodePor
